INSERT INTO CARGO (nome, situacao_registro) VALUES
('Piloto(a)', 1),
('Copiloto(a)', 1),
('Comissário(a) de Bordo', 1),
('Mecânico(a) de Aeronaves', 1),
('Engenheiro(a) de Voo', 1),
('Controlador(a) de Tráfego', 1),
('Supervisor(a) de Manutenção', 1),
('Técnico(a) de Operações', 1),
('Agente de Check-in', 1),
('Agente de Embarque', 1),
('Coordenador(a) de Voo', 1),
('Instrutor(a) de Voo', 1),
('Analista de Segurança', 1),
('Diretor(a) de Operações', 1),
('Gerente de Tripulação', 1),
('Auxiliar de Rampa', 1),
('Despachante Operacional', 1),
('Agente de Carga Aérea', 1),
('Coordenador(a) de Escala', 1),
('Analista de Meteorologia', 1);