insert into PAIS (id_pais, nome) values (132, 'AFEGANISTAO');
insert into PAIS (id_pais, nome) values (175, 'ALBANIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (230, 'ALEMANHA');
insert into PAIS (id_pais, nome) values (310, 'BURKINA FASO');
insert into PAIS (id_pais, nome) values (370, 'ANDORRA');
insert into PAIS (id_pais, nome) values (400, 'ANGOLA');
insert into PAIS (id_pais, nome) values (418, 'ANGUILLA');
insert into PAIS (id_pais, nome) values (434, 'ANTIGUA E BARBUDA');
insert into PAIS (id_pais, nome) values (477, 'ANTILHAS HOLANDESAS');
insert into PAIS (id_pais, nome) values (531, 'ARABIA SAUDITA');
insert into PAIS (id_pais, nome) values (590, 'ARGELIA');
insert into PAIS (id_pais, nome) values (639, 'ARGENTINA');
insert into PAIS (id_pais, nome) values (647, 'ARMENIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (655, 'ARUBA');
insert into PAIS (id_pais, nome) values (698, 'AUSTRALIA');
insert into PAIS (id_pais, nome) values (728, 'AUSTRIA');
insert into PAIS (id_pais, nome) values (736, 'AZERBAIJAO, REPUBLICA DO');
insert into PAIS (id_pais, nome) values (779, 'BAHAMAS, ILHAS');
insert into PAIS (id_pais, nome) values (809, 'BAHREIN, ILHAS');
insert into PAIS (id_pais, nome) values (817, 'BANGLADESH');
insert into PAIS (id_pais, nome) values (833, 'BARBADOS');
insert into PAIS (id_pais, nome) values (850, 'BELARUS, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (876, 'BELGICA');
insert into PAIS (id_pais, nome) values (884, 'BELIZE');
insert into PAIS (id_pais, nome) values (906, 'BERMUDAS');
insert into PAIS (id_pais, nome) values (930, 'MIANMAR (BIRMANIA)');
insert into PAIS (id_pais, nome) values (973, 'BOLIVIA');
insert into PAIS (id_pais, nome) values (981, 'BOSNIA-HERZEGOVINA (REPUBLICA DA)');
insert into PAIS (id_pais, nome) values (1015, 'BOTSUANA');
insert into PAIS (id_pais, nome) values (1058, 'BRASIL');
insert into PAIS (id_pais, nome) values (1082, 'BRUNEI');
insert into PAIS (id_pais, nome) values (1112, 'BULGARIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (1155, 'BURUNDI');
insert into PAIS (id_pais, nome) values (1198, 'BUTAO');
insert into PAIS (id_pais, nome) values (1279, 'CABO VERDE, REPUBLICA DE');
insert into PAIS (id_pais, nome) values (1376, 'CAYMAN, ILHAS');
insert into PAIS (id_pais, nome) values (1414, 'CAMBOJA');
insert into PAIS (id_pais, nome) values (1457, 'CAMAROES');
insert into PAIS (id_pais, nome) values (1490, 'CANADA');
insert into PAIS (id_pais, nome) values (1504, 'CANAL, ILHAS DO (JERSEY E GUERNSEY)');
insert into PAIS (id_pais, nome) values (1511, 'CANARIAS, ILHAS');
insert into PAIS (id_pais, nome) values (1538, 'CAZAQUISTAO, REPUBLICA DO');
insert into PAIS (id_pais, nome) values (1546, 'CATAR');
insert into PAIS (id_pais, nome) values (1589, 'CHILE');
insert into PAIS (id_pais, nome) values (1600, 'CHINA, REPUBLICA POPULAR');
insert into PAIS (id_pais, nome) values (1619, 'FORMOSA (TAIWAN)');
insert into PAIS (id_pais, nome) values (1635, 'CHIPRE');
insert into PAIS (id_pais, nome) values (1651, 'COCOS(KEELING),ILHAS');
insert into PAIS (id_pais, nome) values (1694, 'COLOMBIA');
insert into PAIS (id_pais, nome) values (1732, 'COMORES, ILHAS');
insert into PAIS (id_pais, nome) values (1775, 'CONGO, REPUBLICA DO');
insert into PAIS (id_pais, nome) values (1830, 'COOK, ILHAS');
insert into PAIS (id_pais, nome) values (1872, 'COREIA, REP.POP.DEMOCRATICA');
insert into PAIS (id_pais, nome) values (1902, 'COREIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (1937, 'COSTA DO MARFIM');
insert into PAIS (id_pais, nome) values (1953, 'CROACIA (REPUBLICA DA)');
insert into PAIS (id_pais, nome) values (1961, 'COSTA RICA');
insert into PAIS (id_pais, nome) values (1988, 'COVEITE');
insert into PAIS (id_pais, nome) values (1996, 'CUBA');
insert into PAIS (id_pais, nome) values (2291, 'BENIN');
insert into PAIS (id_pais, nome) values (2321, 'DINAMARCA');
insert into PAIS (id_pais, nome) values (2356, 'DOMINICA,ILHA');
insert into PAIS (id_pais, nome) values (2399, 'EQUADOR');
insert into PAIS (id_pais, nome) values (2402, 'EGITO');
insert into PAIS (id_pais, nome) values (2445, 'EMIRADOS ARABES UNIDOS');
insert into PAIS (id_pais, nome) values (2453, 'ESPANHA');
insert into PAIS (id_pais, nome) values (2461, 'ESLOVENIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (2470, 'ESLOVACA, REPUBLICA');
insert into PAIS (id_pais, nome) values (2496, 'ESTADOS UNIDOS');
insert into PAIS (id_pais, nome) values (2518, 'ESTONIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (2534, 'ETIOPIA');
insert into PAIS (id_pais, nome) values (2550, 'FALKLAND (ILHAS MALVINAS)');
insert into PAIS (id_pais, nome) values (2593, 'FEROE, ILHAS');
insert into PAIS (id_pais, nome) values (2674, 'FILIPINAS');
insert into PAIS (id_pais, nome) values (2712, 'FINLANDIA');
insert into PAIS (id_pais, nome) values (2755, 'FRANCA');
insert into PAIS (id_pais, nome) values (2810, 'GABAO');
insert into PAIS (id_pais, nome) values (2852, 'GAMBIA');
insert into PAIS (id_pais, nome) values (2895, 'GANA');
insert into PAIS (id_pais, nome) values (2917, 'GEORGIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (2933, 'GIBRALTAR');
insert into PAIS (id_pais, nome) values (2976, 'GRANADA');
insert into PAIS (id_pais, nome) values (3018, 'GRECIA');
insert into PAIS (id_pais, nome) values (3050, 'GROENLANDIA');
insert into PAIS (id_pais, nome) values (3093, 'GUADALUPE');
insert into PAIS (id_pais, nome) values (3131, 'GUAM');
insert into PAIS (id_pais, nome) values (3174, 'GUATEMALA');
insert into PAIS (id_pais, nome) values (3255, 'GUIANA FRANCESA');
insert into PAIS (id_pais, nome) values (3298, 'GUINE');
insert into PAIS (id_pais, nome) values (3310, 'GUINE-EQUATORIAL');
insert into PAIS (id_pais, nome) values (3344, 'GUINE-BISSAU');
insert into PAIS (id_pais, nome) values (3379, 'GUIANA');
insert into PAIS (id_pais, nome) values (3417, 'HAITI');
insert into PAIS (id_pais, nome) values (3450, 'HONDURAS');
insert into PAIS (id_pais, nome) values (3514, 'HONG KONG');
insert into PAIS (id_pais, nome) values (3557, 'HUNGRIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (3573, 'IEMEN');
insert into PAIS (id_pais, nome) values (3595, 'MAN, ILHA DE');
insert into PAIS (id_pais, nome) values (3611, 'INDIA');
insert into PAIS (id_pais, nome) values (3654, 'INDONESIA');
insert into PAIS (id_pais, nome) values (3697, 'IRAQUE');
insert into PAIS (id_pais, nome) values (3727, 'IRA, REPUBLICA ISLAMICA DO');
insert into PAIS (id_pais, nome) values (3751, 'IRLANDA');
insert into PAIS (id_pais, nome) values (3794, 'ISLANDIA');
insert into PAIS (id_pais, nome) values (3832, 'ISRAEL');
insert into PAIS (id_pais, nome) values (3867, 'ITALIA');
insert into PAIS (id_pais, nome) values (3883, 'IUGOSLAVIA, REP.FED.DA');
insert into PAIS (id_pais, nome) values (3913, 'JAMAICA');
insert into PAIS (id_pais, nome) values (3964, 'JOHNSTON, ILHAS');
insert into PAIS (id_pais, nome) values (3999, 'JAPAO');
insert into PAIS (id_pais, nome) values (4030, 'JORDANIA');
insert into PAIS (id_pais, nome) values (4111, 'KIRIBATI');
insert into PAIS (id_pais, nome) values (4200, 'LAOS, REP.POP.DEMOCR.DO');
insert into PAIS (id_pais, nome) values (4260, 'LESOTO');
insert into PAIS (id_pais, nome) values (4278, 'LETONIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (4316, 'LIBANO');
insert into PAIS (id_pais, nome) values (4340, 'LIBERIA');
insert into PAIS (id_pais, nome) values (4383, 'LIBIA');
insert into PAIS (id_pais, nome) values (4405, 'LIECHTENSTEIN');
insert into PAIS (id_pais, nome) values (4421, 'LITUANIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (4456, 'LUXEMBURGO');
insert into PAIS (id_pais, nome) values (4472, 'MACAU');
insert into PAIS (id_pais, nome) values (4499, 'MACEDONIA, ANT.REP.IUGOSLAVA');
insert into PAIS (id_pais, nome) values (4502, 'MADAGASCAR');
insert into PAIS (id_pais, nome) values (4525, 'MADEIRA, ILHA DA');
insert into PAIS (id_pais, nome) values (4553, 'MALASIA');
insert into PAIS (id_pais, nome) values (4588, 'MALAVI');
insert into PAIS (id_pais, nome) values (4618, 'MALDIVAS');
insert into PAIS (id_pais, nome) values (4642, 'MALI');
insert into PAIS (id_pais, nome) values (4677, 'MALTA');
insert into PAIS (id_pais, nome) values (4723, 'MARIANAS DO NORTE');
insert into PAIS (id_pais, nome) values (4740, 'MARROCOS');
insert into PAIS (id_pais, nome) values (4766, 'MARSHALL,ILHAS');
insert into PAIS (id_pais, nome) values (4774, 'MARTINICA');
insert into PAIS (id_pais, nome) values (4855, 'MAURICIO');
insert into PAIS (id_pais, nome) values (4901, 'MIDWAY, ILHAS');
insert into PAIS (id_pais, nome) values (4936, 'MEXICO');
insert into PAIS (id_pais, nome) values (4944, 'MOLDAVIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (4952, 'MONACO');
insert into PAIS (id_pais, nome) values (4979, 'MONGOLIA');
insert into PAIS (id_pais, nome) values (4995, 'MICRONESIA');
insert into PAIS (id_pais, nome) values (5010, 'MONTSERRAT,ILHAS');
insert into PAIS (id_pais, nome) values (5053, 'MOCAMBIQUE');
insert into PAIS (id_pais, nome) values (5070, 'NAMIBIA');
insert into PAIS (id_pais, nome) values (5088, 'NAURU');
insert into PAIS (id_pais, nome) values (5118, 'CHRISTMAS,ILHA (NAVIDAD)');
insert into PAIS (id_pais, nome) values (5177, 'NEPAL');
insert into PAIS (id_pais, nome) values (5215, 'NICARAGUA');
insert into PAIS (id_pais, nome) values (5258, 'NIGER');
insert into PAIS (id_pais, nome) values (5282, 'NIGERIA');
insert into PAIS (id_pais, nome) values (5312, 'NIUE,ILHA');
insert into PAIS (id_pais, nome) values (5355, 'NORFOLK,ILHA');
insert into PAIS (id_pais, nome) values (5380, 'NORUEGA');
insert into PAIS (id_pais, nome) values (5428, 'NOVA CALEDONIA');
insert into PAIS (id_pais, nome) values (5452, 'PAPUA NOVA GUINE');
insert into PAIS (id_pais, nome) values (5487, 'NOVA ZELANDIA');
insert into PAIS (id_pais, nome) values (5517, 'VANUATU');
insert into PAIS (id_pais, nome) values (5568, 'OMA');
insert into PAIS (id_pais, nome) values (5665, 'PACIFICO,ILHAS DO (POSSESSAO DOS EUA)');
insert into PAIS (id_pais, nome) values (5738, 'PAISES BAIXOS (HOLANDA)');
insert into PAIS (id_pais, nome) values (5754, 'PALAU');
insert into PAIS (id_pais, nome) values (5762, 'PAQUISTAO');
insert into PAIS (id_pais, nome) values (5800, 'PANAMA');
insert into PAIS (id_pais, nome) values (5860, 'PARAGUAI');
insert into PAIS (id_pais, nome) values (5894, 'PERU');
insert into PAIS (id_pais, nome) values (5932, 'PITCAIRN,ILHA');
insert into PAIS (id_pais, nome) values (5991, 'POLINESIA FRANCESA');
insert into PAIS (id_pais, nome) values (6033, 'POLONIA, REPUBLICA DA');
insert into PAIS (id_pais, nome) values (6076, 'PORTUGAL');
insert into PAIS (id_pais, nome) values (6114, 'PORTO RICO');
insert into PAIS (id_pais, nome) values (6238, 'QUENIA');
insert into PAIS (id_pais, nome) values (6254, 'QUIRGUIZ, REPUBLICA');
insert into PAIS (id_pais, nome) values (6289, 'REINO UNIDO');
insert into PAIS (id_pais, nome) values (6408, 'REPUBLICA CENTRO-AFRICANA');
insert into PAIS (id_pais, nome) values (6475, 'REPUBLICA DOMINICANA');
insert into PAIS (id_pais, nome) values (6602, 'REUNIAO, ILHA');
insert into PAIS (id_pais, nome) values (6653, 'ZIMBABUE');
insert into PAIS (id_pais, nome) values (6700, 'ROMENIA');
insert into PAIS (id_pais, nome) values (6750, 'RUANDA');
insert into PAIS (id_pais, nome) values (6769, 'RUSSIA, FEDERACAO DA');
insert into PAIS (id_pais, nome) values (6777, 'SALOMAO, ILHAS');
insert into PAIS (id_pais, nome) values (6781, 'SAINT KITTS E NEVIS');
insert into PAIS (id_pais, nome) values (6858, 'SAARA OCIDENTAL');
insert into PAIS (id_pais, nome) values (6874, 'EL SALVADOR');
insert into PAIS (id_pais, nome) values (6912, 'SAMOA AMERICANA');
insert into PAIS (id_pais, nome) values (6955, 'SAO CRISTOVAO E NEVES,ILHAS');
insert into PAIS (id_pais, nome) values (6971, 'SAN MARINO');
insert into PAIS (id_pais, nome) values (7005, 'SAO PEDRO E MIQUELON');
insert into PAIS (id_pais, nome) values (7056, 'SAO VICENTE E GRANADINAS');
insert into PAIS (id_pais, nome) values (7102, 'SANTA HELENA');
insert into PAIS (id_pais, nome) values (7153, 'SANTA LUCIA');
insert into PAIS (id_pais, nome) values (7200, 'SAO TOME E PRINCIPE, ILHAS');
insert into PAIS (id_pais, nome) values (7285, 'SENEGAL');
insert into PAIS (id_pais, nome) values (7315, 'SEYCHELLES');
insert into PAIS (id_pais, nome) values (7358, 'SERRA LEOA');
insert into PAIS (id_pais, nome) values (7412, 'CINGAPURA');
insert into PAIS (id_pais, nome) values (7447, 'SIRIA, REPUBLICA ARABE DA');
insert into PAIS (id_pais, nome) values (7480, 'SOMALIA');
insert into PAIS (id_pais, nome) values (7501, 'SRI LANKA');
insert into PAIS (id_pais, nome) values (7544, 'SUAZILANDIA');
insert into PAIS (id_pais, nome) values (7560, 'AFRICA DO SUL');
insert into PAIS (id_pais, nome) values (7595, 'SUDAO');
insert into PAIS (id_pais, nome) values (7641, 'SUECIA');
insert into PAIS (id_pais, nome) values (7676, 'SUICA');
insert into PAIS (id_pais, nome) values (7706, 'SURINAME');
insert into PAIS (id_pais, nome) values (7722, 'TADJIQUISTAO, REPUBLICA DO');
insert into PAIS (id_pais, nome) values (7765, 'TAILANDIA');
insert into PAIS (id_pais, nome) values (7820, 'TERRITORIO BRIT.OC.INDICO');
insert into PAIS (id_pais, nome) values (7838, 'DJIBUTI');
insert into PAIS (id_pais, nome) values (7889, 'CHADE');
insert into PAIS (id_pais, nome) values (7919, 'TCHECA, REPUBLICA');
insert into PAIS (id_pais, nome) values (7951, 'TIMOR LESTE');
insert into PAIS (id_pais, nome) values (8001, 'TOGO');
insert into PAIS (id_pais, nome) values (8052, 'TOQUELAU,ILHAS');
insert into PAIS (id_pais, nome) values (8109, 'TONGA');
insert into PAIS (id_pais, nome) values (8150, 'TRINIDAD E TOBAGO');
insert into PAIS (id_pais, nome) values (8206, 'TUNISIA');
insert into PAIS (id_pais, nome) values (8230, 'TURCAS E CAICOS,ILHAS');
insert into PAIS (id_pais, nome) values (8249, 'TURCOMENISTAO, REPUBLICA DO');
insert into PAIS (id_pais, nome) values (8273, 'TURQUIA');
insert into PAIS (id_pais, nome) values (8281, 'TUVALU');
insert into PAIS (id_pais, nome) values (8311, 'UCRANIA');
insert into PAIS (id_pais, nome) values (8338, 'UGANDA');
insert into PAIS (id_pais, nome) values (8451, 'URUGUAI');
insert into PAIS (id_pais, nome) values (8478, 'UZBEQUISTAO, REPUBLICA DO');
insert into PAIS (id_pais, nome) values (8486, 'VATICANO, EST.DA CIDADE DO');
insert into PAIS (id_pais, nome) values (8508, 'VENEZUELA');
insert into PAIS (id_pais, nome) values (8583, 'VIETNA');
insert into PAIS (id_pais, nome) values (8630, 'VIRGENS,ILHAS (BRITANICAS)');
insert into PAIS (id_pais, nome) values (8664, 'VIRGENS,ILHAS (E.U.A.)');
insert into PAIS (id_pais, nome) values (8702, 'FIJI');
insert into PAIS (id_pais, nome) values (8737, 'WAKE, ILHA');
insert into PAIS (id_pais, nome) values (8907, 'ZAMBIA');
insert into PAIS (id_pais, nome) values (8958, 'ZONA DO CANAL DO PANAMA');