INSERT INTO TIPO_EXAME (descricao, situacao_registro) VALUES
('Exame Teórico de Piloto Privado (PPA)', 1),
('Exame Prático de Piloto Privado (PPA)', 1),
('Exame Teórico de Piloto Comercial (CPL)', 1),
('Exame Prático de Piloto Comercial (CPL)', 1),
('Exame Teórico de Piloto de Linha Aérea (ATPL)', 1),
('Exame Prático de Piloto de Linha Aérea (ATPL)', 1),
('Exame Médico Aeronáutico (CMA)', 1),
('Exame de Proficiência em Inglês (ICAO)', 1),
('Exame de Navegação Aérea', 1),
('Exame de Meteorologia Aeronáutica', 1),
('Exame de Regulamentos de Tráfego Aéreo', 1),
('Exame de Emergências e Sobrevivência Aérea', 1),
('Exame de Conhecimentos Técnicos de Aeronaves', 1),
('Exame de Manobras e Procedimentos de Voo', 1),
('Exame de Performance e Planejamento de Voo', 1),
('Exame de Simulador de Voo', 1),
('Exame de Radiofonia Aeronáutica', 1),
('Exame de Procedimentos IFR (Instrument Flight Rules)', 1),
('Exame de Segurança de Voo', 1),
('Exame de Operação e Manuseio de Sistemas de Aeronaves', 1);