INSERT INTO TIPO_CERTIFICADO (descricao, situacao_registro) VALUES
('Certificado de Piloto Privado (PPA)', 1),
('Certificado de Piloto Comercial (CPL)', 1),
('Certificado de Piloto de Linha Aérea (ATPL)', 1),
('Certificado de Instrutor de Voo', 1),
('Certificado de Comissário de Bordo', 1),
('Certificado de Mecânico de Aeronaves', 1),
('Certificado de Despachante Operacional', 1),
('Certificado de Controlador de Tráfego Aéreo', 1),
('Certificado de Segurança de Voo', 1),
('Certificado de Primeiros Socorros Aeronáuticos', 1),
('Certificado de Operador de Carga Aérea', 1),
('Certificado de Manutenção de Aeronaves', 1),
('Certificado de Transporte de Materiais Perigosos', 1),
('Certificado de Segurança Aeroportuária', 1),
('Certificado de Navegação Aérea', 1),
('Certificado de Atendimento ao Passageiro', 1),
('Certificado de Investigação de Acidentes Aeronáuticos', 1),
('Certificado de Instrutor de Simulador de Voo', 1),
('Certificado de Operador de Equipamentos Aeroportuários', 1),
('Certificado de Meteorologia Aeronáutica', 1);