INSERT INTO TIPO_LICENCA (descricao, situacao_registro) VALUES
('Licença de Piloto Privado (PPA)', 1),
('Licença de Piloto Comercial (CPL)', 1),
('Licença de Piloto de Linha Aérea (ATPL)', 1),
('Licença de Instrutor de Voo', 1),
('Licença de Comissário de Bordo', 1),
('Licença de Mecânico de Aeronaves', 1),
('Licença de Despachante Operacional', 1),
('Licença de Controlador de Tráfego Aéreo', 1),
('Licença de Operador de RPA (Drones)', 1),
('Licença de Operador de Radiofonia Aeronáutica', 1),
('Licença de Piloto de Helicóptero', 1),
('Licença de Piloto de Balão', 1),
('Licença de Piloto de Aeronaves Anfíbias', 1),
('Licença de Piloto de Aeronaves Experimentais', 1),
('Licença de Instrutor de Simulador de Voo', 1),
('Licença de Piloto Agrícola', 1),
('Licença de Piloto de Planador', 1),
('Licença de Especialista em Segurança de Voo', 1),
('Licença de Especialista em Manutenção Aeronáutica', 1),
('Licença de Investigador de Acidentes Aeronáuticos', 1);