INSERT INTO TIPO_TREINAMENTO (descricao, situacao_registro) VALUES
('Treinamento Básico de Piloto Privado', 1),
('Treinamento Avançado de Piloto Comercial', 1),
('Treinamento de Piloto de Linha Aérea', 1),
('Treinamento de Voo por Instrumentos (IFR)', 1),
('Treinamento de Simulador de Voo', 1),
('Treinamento de Emergências e Sobrevivência Aérea', 1),
('Treinamento de Radiofonia Aeronáutica', 1),
('Treinamento de Meteorologia Aeronáutica', 1),
('Treinamento de Manutenção Preventiva de Aeronaves', 1),
('Treinamento de Regulamentos e Procedimentos de Voo', 1),
('Treinamento de Navegação Aérea', 1),
('Treinamento de Decolagem e Pouso', 1),
('Treinamento de Pilotagem Noturna', 1),
('Treinamento de Operação de Aeronaves Multimotores', 1),
('Treinamento de Segurança de Voo', 1),
('Treinamento de Transporte de Carga Aérea', 1),
('Treinamento de Manuseio de Materiais Perigosos', 1),
('Treinamento de Atendimento ao Passageiro', 1),
('Treinamento de Controle de Tráfego Aéreo', 1),
('Treinamento de Investigação de Acidentes Aeronáuticos', 1);