INSERT INTO TITULACAO (descricao, situacao_registro) VALUES
('Bacharel em Aviação Civil', 1),
('Técnico em Manutenção de Aeronaves', 1),
('Piloto Comercial', 1),
('Piloto de Linha Aérea', 1),
('Especialização em Segurança de Voo', 1),
('Controlador de Tráfego Aéreo', 1),
('Engenheiro Aeronáutico', 1),
('Instrutor de Voo', 1),
('Comissário de Bordo Certificado', 1),
('Técnico em Operações Aeroportuárias', 1),
('Especialização em Meteorologia Aeronáutica', 1),
('MBA em Gestão Aeroportuária', 1),
('Despachante Operacional Certificado', 1),
('Mestre em Engenharia Aeronáutica', 1),
('Doutor em Ciências Aeronáuticas', 1),
('Especialização em Manutenção de Aeronaves', 1),
('Analista de Segurança de Aviação', 1),
('Especialização em Logística Aérea', 1),
('Técnico em Sistemas de Navegação Aérea', 1),
('Curso de Sobrevivência e Emergência Aérea', 1);